### ISSUE TITLE
Pip dependency problem when installing musif

### ISSUE THREAD

**Issue by johentsch** [DIDONEproject/musif#56] opened 2023-03-02 09:45 UTC
**Steps to reproduce**

* Set up new environment with `python==3.10.9`
* `pip install musif` (with `pip==22.3.1`)

**Bug report**

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyproject-api 1.5.0 requires tomli>=2.0.1; python_version < "3.11", which is not installed.
```

**Comment by 00sapo** [comment] 2023-04-03 15:15
Thank you very much for this issue!

I cannot reproduce your issue on Linux. Which OS are you using? Could you write here step by step how you get into this error? Also, try to upgrade pip before installing: `python -m pip install --upgrade pip`

**Comment by johentsch** [comment] 2023-04-04 12:05
The same error shows up with pip 23.0.1 on Linux. Since it's a dependency conflict caused by `pyproject-api` it's most likely not an OS problem. Then again, I don't think it's a blocker for using musif.

**Comment by 00sapo** [comment] 2023-04-05 16:47
It looks like your set up is not installing tomli for some reason. This is weird because tomli is a pure python package that comes in tar.gz, no wheel needed at all. I think it could be an issue with your environment. Have you tried installing musif in a fresh environment? Can you write the steps you follows to reproduce the issue?

I would be especially interested in the output of the following commands (run inside your environment):

* `which python`
* `python --version`
* `python -m pip --version`
* `python -m pip freeze`

Thanks!

**Comment by martianbug** [comment] 2023-07-20 11:03
I couldn't replicate this on 3.11 or 3.10.9 either, so I'll close the issue for now.

**Closed by martianbug** 2023-07-20 11:03 UTC
